<?php

// Canonical provider metadata used by the account form and the read-only catalog API.
// Credentials are field names only; secret values must never be stored in this file.
return [
    'providers' => [
        [
            'slug' => 'aliyun',
            'name' => '阿里云',
            'category' => 'cloud',
            'description' => '阿里云 ECS OpenAPI（RAM AccessKey，按服务与区域选择 Endpoint）',
            'docs_url' => 'https://help.aliyun.com/zh/ecs/developer-reference/api-ecs-2014-05-26-overview',
            'base_url' => 'https://ecs.aliyuncs.com',
            'auth' => 'access_key',
            'credential_fields' => ['access_key_id', 'access_key_secret', 'region_id'],
            'required_credential_fields' => ['access_key_id', 'access_key_secret'],
            'requires_region' => true,
        ],
        [
            'slug' => 'tencent-cloud',
            'name' => '腾讯云',
            'category' => 'cloud',
            'description' => '腾讯云 API 3.0（TC3-HMAC-SHA256）',
            'docs_url' => 'https://cloud.tencent.com/document/product/1278/46660',
            'base_url' => 'https://cvm.tencentcloudapi.com',
            'auth' => 'secret_id',
            'credential_fields' => ['secret_id', 'secret_key', 'region'],
            'required_credential_fields' => ['secret_id', 'secret_key'],
            'requires_region' => true,
        ],
        [
            'slug' => 'huawei-cloud',
            'name' => '华为云',
            'category' => 'cloud',
            'description' => '华为云 API（AK/SK 签名或 IAM Token，区域 Endpoint）',
            'docs_url' => 'https://support.huaweicloud.com/intl/en-us/api-iam/iam_04_0001.html',
            'base_url' => 'https://ecs.cn-north-4.myhuaweicloud.com',
            'auth' => 'ak_sk',
            'credential_fields' => ['access_key', 'secret_key', 'project_id', 'region'],
            'required_credential_fields' => ['access_key', 'secret_key', 'project_id'],
            'requires_region' => true,
        ],
        [
            'slug' => 'aws',
            'name' => '亚马逊云 AWS',
            'category' => 'cloud',
            'description' => 'Amazon Web Services API（SigV4）',
            'docs_url' => 'https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv.html',
            'base_url' => 'https://ec2.amazonaws.com',
            'auth' => 'access_key',
            'credential_fields' => ['access_key_id', 'secret_access_key', 'region'],
            'required_credential_fields' => ['access_key_id', 'secret_access_key'],
            'requires_region' => true,
        ],
        [
            'slug' => 'google-cloud',
            'name' => 'Google Cloud',
            'category' => 'cloud',
            'description' => 'Google Cloud API（Service Account / OAuth 2.0）',
            'docs_url' => 'https://cloud.google.com/docs/authentication/provide-credentials-adc',
            'base_url' => 'https://compute.googleapis.com',
            'auth' => 'service_account',
            'credential_fields' => ['project_id', 'service_account_json'],
            'required_credential_fields' => ['service_account_json'],
        ],
        [
            'slug' => 'cloudflare',
            'name' => 'Cloudflare',
            'category' => 'domain',
            'description' => 'Cloudflare REST API（受限 API Token，或 Global API Key + 账户邮箱）',
            'docs_url' => 'https://developers.cloudflare.com/api/',
            'base_url' => 'https://api.cloudflare.com/client/v4',
            'auth' => 'api_token',
            'credential_fields' => ['api_token', 'api_email', 'account_id'],
            'required_credential_fields' => ['api_token'],
        ],
        [
            'slug' => 'aliyun-domains',
            'name' => '阿里云万网（域名）',
            'category' => 'domain',
            'description' => '阿里云域名 OpenAPI（2018-01-29，与 RAM AccessKey 共用）',
            'docs_url' => 'https://help.aliyun.com/zh/domain/api-domain-2018-01-29-overview',
            'base_url' => 'https://domain.aliyuncs.com',
            'auth' => 'access_key',
            'credential_fields' => ['access_key_id', 'access_key_secret'],
            'required_credential_fields' => ['access_key_id', 'access_key_secret'],
        ],
        [
            'slug' => 'west-cn',
            'name' => '西部数码',
            'category' => 'domain',
            'description' => '西部数码域名 API v2（正式合作商、GBK 编码）',
            'docs_url' => 'https://www.west.cn/CustomerCenter/doc/domain_v2.html',
            'base_url' => 'https://api.west.cn/api/v2',
            'auth' => 'md5_token',
            'credential_fields' => ['username', 'api_password'],
            'required_credential_fields' => ['username', 'api_password'],
        ],
        [
            'slug' => 'spaceship',
            'name' => 'Spaceship',
            'category' => 'domain',
            'description' => 'Spaceship API（X-Api-Key / X-Api-Secret）',
            'docs_url' => 'https://docs.spaceship.dev/#section/Spaceship-API',
            'base_url' => 'https://spaceship.dev/api',
            'auth' => 'api_key_secret',
            'credential_fields' => ['api_key', 'api_secret'],
            'required_credential_fields' => ['api_key', 'api_secret'],
        ],
        [
            'slug' => 'mofang-finance',
            'name' => '魔方财务系统',
            'category' => 'billing',
            'description' => '魔方财务 API；服务地址由租户填写，登录换取 JWT',
            'docs_url' => 'http://w2.test.idcsmart.com/doc',
            'base_url' => null,
            'base_url_mode' => 'custom',
            'auth' => 'jwt_login',
            'credential_fields' => ['base_url', 'account', 'api_secret'],
            'required_credential_fields' => ['account', 'api_secret'],
        ],
        [
            'slug' => 'idcsmart-v10',
            'name' => '魔方业务系统 V10',
            'category' => 'billing',
            'description' => 'IDCsmart V10 前台 API；服务地址和用户 Bearer Token 由部署实例提供',
            'docs_url' => 'https://docs.idcsmart.com/docs/API%E6%96%87%E6%A1%A3',
            'base_url' => null,
            'base_url_mode' => 'custom',
            'auth' => 'bearer_token',
            'credential_fields' => ['base_url', 'bearer_token'],
            'required_credential_fields' => ['bearer_token'],
        ],
    ],
];
